import { useEffect, useState } from "react";
import { FileText, Plus } from "lucide-react";
import { Link } from "react-router-dom";
import { api, json } from "../lib/api.js";
import { Badge, Button, EmptyState, ErrorNotice, Field, Loading, Modal, PageTitle, formatDate, useToast } from "../components/common.jsx";

export default function NotesPage() {
  const [items, setItems] = useState([]); const [projects, setProjects] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(false); const [projectId, setProjectId] = useState(""); const [content, setContent] = useState(""); const [formError, setFormError] = useState(""); const [busy, setBusy] = useState(false); const { showToast, toastElement } = useToast();
  async function load() { setLoading(true); setError(""); try { const projects = await api("/project"); setProjects(projects); const noteGroups = await Promise.all(projects.map(async ({ project, role }) => ({ project, role, notes: await api(`/notes/${project._id}`) }))); setItems(noteGroups.flatMap((group) => group.notes.map((note) => ({ ...note, project: group.project, projectRole: group.role })))); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const adminProjects = projects.filter((item) => item.role === "admin");
  async function addNote(event) { event.preventDefault(); setBusy(true); setFormError(""); try { await api(`/notes/${projectId}`, json("POST", { content })); setModal(false); setContent(""); await load(); showToast("Note added."); } catch (err) { setFormError(err.message); } finally { setBusy(false); } }
  if (loading) return <Loading />;
  return <div className="page-stack"><PageTitle eyebrow="SHARED CONTEXT" title="Project notes" description="Decisions, updates, and details your team wants to keep close." action={adminProjects.length > 0 && <Button onClick={() => { setProjectId(adminProjects[0].project._id); setModal(true); }}><Plus size={16} />Add note</Button>} />{error && <ErrorNotice error={{ message: error }} onRetry={load} />}{items.length ? <div className="notes-grid notes-grid-global">{items.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).map((note) => <article className="note-card" key={note._id}><div className="note-card-top"><Link className="note-project-link" to={`/projects/${note.project._id}?tab=notes`}>{note.project.name}</Link><Badge>{note.projectRole?.replace("_", " ")}</Badge></div><p>{note.content}</p><div className="note-card-foot"><span>{note.createdBy?.fullName || note.createdBy?.username || "A teammate"}</span><span>{formatDate(note.createdAt)}</span></div></article>)}</div> : <EmptyState icon={FileText} title="No notes shared yet" description="When your project Admin adds a note, it will show up here." action={adminProjects.length > 0 && <Button onClick={() => { setProjectId(adminProjects[0].project._id); setModal(true); }}><Plus size={15} />Add a note</Button>} />}{modal && <Modal title="Add a project note" onClose={() => setModal(false)} wide><form className="form-stack" onSubmit={addNote}><Field as="select" label="Project" name="projectId" value={projectId} onChange={(event) => setProjectId(event.target.value)}>{adminProjects.map(({ project }) => <option key={project._id} value={project._id}>{project.name}</option>)}</Field><Field as="textarea" label="Note" name="content" value={content} onChange={(event) => setContent(event.target.value)} required maxLength={10000} rows={8} autoFocus placeholder="Write a decision, update, or detail the team should remember…" />{formError && <p className="form-error" role="alert">{formError}</p>}<div className="modal-actions"><Button type="button" variant="quiet" onClick={() => setModal(false)}>Cancel</Button><Button type="submit" disabled={busy || !projectId}>{busy ? "Saving…" : "Save note"}</Button></div></form></Modal>}{toastElement}</div>;
}
