import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Check, KeyRound, Moon, Sun, UserRound } from "lucide-react";
import { api, json } from "../lib/api.js";
import { useAuth } from "../lib/auth.jsx";
import { Avatar, Button, Field, PageTitle } from "../components/common.jsx";

export default function SettingsPage() {
  const { user, signOut } = useAuth(); const navigate = useNavigate(); const [dark, setDark] = useState(() => (localStorage.getItem("taskforge-theme") || "light") === "dark"); const [form, setForm] = useState({ oldPassword: "", newPassword: "" }); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [busy, setBusy] = useState(false);
  function toggleTheme() { const next = !dark; setDark(next); localStorage.setItem("taskforge-theme", next ? "dark" : "light"); document.documentElement.dataset.theme = next ? "dark" : "light"; }
  async function changePassword(event) { event.preventDefault(); setError(""); setSuccess(""); setBusy(true); try { await api("/auth/change-password", json("POST", form)); setSuccess("Password changed. Please sign in again."); await signOut(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="page-stack"><PageTitle eyebrow="YOUR ACCOUNT" title="Settings" description="Manage your account and sign-in details." action={<Button variant="secondary" onClick={() => navigate("/dashboard")}><ArrowLeft size={15} />Back to workspace</Button>} /><section className="panel settings-profile"><span className="settings-icon"><UserRound size={18} /></span><div><p className="eyebrow">PROFILE</p><h2>{user?.fullName || user?.username}</h2><p>{user?.email}</p></div><Avatar user={user} size="large" /></section><section className="panel section-panel theme-panel"><div><p className="eyebrow">APPEARANCE</p><h2>Dark theme</h2><p className="muted">Choose a comfortable look for your workspace.</p></div><button type="button" className={`theme-switch ${dark ? "is-on" : ""}`} role="switch" aria-checked={dark} aria-label="Toggle dark theme" onClick={toggleTheme}><span>{dark ? <Moon size={14} /> : <Sun size={14} />}</span><span>{dark ? "On" : "Off"}</span></button></section><section className="panel section-panel settings-password"><div className="section-heading"><div className="heading-with-icon"><span className="settings-icon"><KeyRound size={18} /></span><div><p className="eyebrow">ACCOUNT SECURITY</p><h2>Change password</h2></div></div></div><form className="settings-form" onSubmit={changePassword}><Field label="Current password" name="oldPassword" type="password" autoComplete="current-password" required value={form.oldPassword} onChange={(event) => setForm({ ...form, oldPassword: event.target.value })} /><Field label="New password" name="newPassword" type="password" autoComplete="new-password" required minLength={6} value={form.newPassword} onChange={(event) => setForm({ ...form, newPassword: event.target.value })} hint="Use at least 6 characters." />{error && <p className="form-error" role="alert">{error}</p>}{success && <p className="success-message"><Check size={15} />{success}</p>}<Button type="submit" disabled={busy}>{busy ? "Updating…" : "Update password"}</Button></form></section><p className="settings-footnote">Your profile details are managed from your TaskForge account.</p></div>;
}
