import { useEffect, useRef, useState } from "react";
import { ArrowLeft, Check, CheckCheck, Download, FilePlus2, ListTodo, Paperclip, Pencil, Plus, Trash2 } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, json } from "../lib/api.js";
import { useAuth } from "../lib/auth.jsx";
import { Badge, Button, EmptyState, ErrorNotice, Field, Loading, PageTitle, formatDate, formatStatus, useToast } from "../components/common.jsx";
import { Modal } from "../components/common.jsx";

export default function TaskDetailPage() {
  const { projectId, taskId } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [task, setTask] = useState(null); const [role, setRole] = useState("member"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [subtaskTitle, setSubtaskTitle] = useState(""); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(false); const [taskForm, setTaskForm] = useState({ title: "", description: "", assignedTo: "", status: "todo" }); const [formError, setFormError] = useState(""); const fileInput = useRef(null); const { showToast, toastElement } = useToast();
  const canManage = ["admin", "project_admin"].includes(role); const canUpdateStatus = canManage || String(task?.assignedTo?._id || task?.assignedTo || "") === String(user?._id);
  async function load() { setLoading(true); setError(""); try { const [detail, members, project] = await Promise.all([api(`/tasks/${projectId}/t/${taskId}`), api(`/project/${projectId}/members`), api(`/project/${projectId}`)]); setTask({ ...detail, project, members }); const membership = members.find((member) => String(member.user?._id) === String(user?._id)); setRole(membership?.role || "member"); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [projectId, taskId, user?._id]);
  async function updateStatus(status) { try { const updated = await api(`/tasks/${projectId}/t/${taskId}`, json("PUT", { status })); setTask({ ...task, ...updated, project: task.project, subtasks: task.subtasks, members: task.members }); showToast("Task status updated."); } catch (err) { showToast(err.message); } }
  function openEdit() { setTaskForm({ title: task.title, description: task.description || "", assignedTo: task.assignedTo?._id || "", status: task.status, dueDate: task.dueDate ? String(task.dueDate).slice(0, 10) : "" }); setFormError(""); setEditing(true); }
  async function saveTask(event) { event.preventDefault(); setBusy(true); setFormError(""); try { const updated = await api(`/tasks/${projectId}/t/${taskId}`, json("PUT", { ...taskForm, assignedTo: taskForm.assignedTo || null, dueDate: taskForm.dueDate || null })); setTask({ ...updated, project: task.project, subtasks: task.subtasks }); setEditing(false); showToast("Task updated."); } catch (err) { setFormError(err.message); } finally { setBusy(false); } }
  async function addSubtask(event) { event.preventDefault(); setBusy(true); try { await api(`/tasks/${projectId}/t/${taskId}/subtasks`, json("POST", { title: subtaskTitle })); setSubtaskTitle(""); await load(); showToast("Subtask added."); } catch (err) { showToast(err.message); } finally { setBusy(false); } }
  async function updateSubtaskStatus(subtask, status) { try { await api(`/tasks/${projectId}/st/${subtask._id}`, json("PUT", { status })); await load(); } catch (err) { showToast(err.message); } }
  async function editSubtask(subtask) { const title = window.prompt("Update subtask title", subtask.title); if (title === null || !title.trim()) return; try { await api(`/tasks/${projectId}/st/${subtask._id}`, json("PUT", { title: title.trim() })); await load(); showToast("Subtask updated."); } catch (err) { showToast(err.message); } }
  async function deleteSubtask(subtask) { if (!window.confirm(`Delete “${subtask.title}”?`)) return; try { await api(`/tasks/${projectId}/st/${subtask._id}`, { method: "DELETE" }); await load(); showToast("Subtask deleted."); } catch (err) { showToast(err.message); } }
  async function uploadFiles(event) { const files = [...(event.target.files || [])]; if (!files.length) return; const form = new FormData(); files.forEach((file) => form.append("attachments", file)); setBusy(true); try { await api(`/tasks/${projectId}/t/${taskId}/attachments`, { method: "POST", body: form }); await load(); showToast("Attachments uploaded."); } catch (err) { showToast(err.message); } finally { setBusy(false); event.target.value = ""; } }
  async function deleteTask() { if (!window.confirm("Delete this task and its subtasks?")) return; try { await api(`/tasks/${projectId}/t/${taskId}`, { method: "DELETE" }); navigate(`/projects/${projectId}?tab=tasks`); } catch (err) { showToast(err.message); } }
  if (loading) return <Loading label="Loading task" />;
  if (error) return <div className="page-stack"><Link className="back-link" to={`/projects/${projectId}?tab=tasks`}><ArrowLeft size={15} />Back to project</Link><ErrorNotice error={{ message: error }} onRetry={load} /></div>;
  const doneCount = task.subtasks.filter((subtask) => subtask.isCompleted).length;
  return <div className="page-stack"><Link className="back-link" to={`/projects/${projectId}?tab=tasks`}><ArrowLeft size={15} />{task.project?.name || "Back to project"}</Link><PageTitle eyebrow="TASK DETAILS" title={task.title} description={task.description || "A clear next step for this project."} action={canManage && <><Button variant="quiet" onClick={openEdit}><Pencil size={15} />Edit task</Button><Button variant="quiet" className="danger-button" onClick={deleteTask}><Trash2 size={16} />Delete task</Button></>} />
    <div className="task-detail-grid"><div className="task-detail-main"><section className="panel task-properties"><div className="section-heading"><div><p className="eyebrow">TASK STATUS</p><h2>Progress</h2></div><Badge tone={task.status === "in_progress" ? "dark" : "neutral"}>{formatStatus(task.status)}</Badge></div>{canUpdateStatus ? <div className="status-options">{[["todo", "Not started"], ["in_progress", "In progress"], ["done", "Done"]].map(([value, label]) => <button key={value} className={`status-option ${task.status === value ? "status-option-active" : ""}`} onClick={() => updateStatus(value)}>{task.status === value && <Check size={15} />}{label}</button>)}</div> : <p className="muted">Your project admin can assign this task to you so you can update its progress.</p>}<div className="task-meta-grid"><div><span>Assigned to</span><strong>{task.assignedTo?.fullName || (task.assignedTo ? `@${task.assignedTo.username}` : "Unassigned")}</strong></div><div><span>Created by</span><strong>{task.assignedBy?.fullName || task.assignedBy?.username || "—"}</strong></div><div><span>Due date</span><strong>{task.dueDate ? formatDate(task.dueDate) : "Not scheduled"}</strong></div><div><span>Created</span><strong>{formatDate(task.createdAt)}</strong></div><div><span>Last updated</span><strong>{formatDate(task.updatedAt)}</strong></div></div></section>
      <section className="panel section-panel"><div className="section-heading"><div><p className="eyebrow">BREAK IT DOWN</p><h2>Subtasks <span className="heading-count">{doneCount}/{task.subtasks.length}</span></h2></div><span className="muted small-copy">{task.subtasks.length ? `${Math.round(doneCount / task.subtasks.length * 100)}% complete` : ""}</span></div>{task.subtasks.length ? <div className="subtask-list">{task.subtasks.map((subtask) => <div className={`subtask-row ${subtask.isCompleted ? "subtask-done" : ""}`} key={subtask._id}><span className="subtask-copy"><strong>{subtask.title}</strong><small>Added {formatDate(subtask.createdAt)}</small></span><select className="subtask-status" aria-label={`Progress for ${subtask.title}`} value={subtask.status || (subtask.isCompleted ? "done" : "todo")} onChange={(event) => updateSubtaskStatus(subtask, event.target.value)}><option value="todo">Not started</option><option value="in_progress">In progress</option><option value="done">Done</option></select>{canManage && <div className="row-actions"><button className="text-button" onClick={() => editSubtask(subtask)}>Edit</button><button className="icon-button" onClick={() => deleteSubtask(subtask)} aria-label="Delete subtask"><Trash2 size={15} /></button></div>}</div>)}</div> : <EmptyState icon={CheckCheck} title="No subtasks yet" description={canManage ? "Break this task into small, finishable pieces." : "The project manager hasn’t added subtasks yet."} />}{canManage && <form className="inline-create" onSubmit={addSubtask}><input aria-label="New subtask title" value={subtaskTitle} onChange={(event) => setSubtaskTitle(event.target.value)} maxLength={200} required placeholder="Add a subtask" /><Button variant="quiet" type="submit" disabled={busy}><Plus size={16} />Add</Button></form>}</section>
      <section className="panel section-panel"><div className="section-heading"><div><p className="eyebrow">FILES</p><h2>Attachments <span className="heading-count">{task.attachments.length}</span></h2></div><input ref={fileInput} type="file" multiple accept="image/jpeg,image/png,image/gif,image/webp,application/pdf" hidden onChange={uploadFiles} /><Button variant="quiet" onClick={() => fileInput.current?.click()} disabled={busy}><FilePlus2 size={16} />Add files</Button></div>{task.attachments.length ? <div className="attachment-list">{task.attachments.map((file) => <a className="attachment-row" key={file._id || file.url} href={file.url} target="_blank" rel="noreferrer"><span className="attachment-icon"><Paperclip size={16} /></span><span><strong>{decodeURIComponent(file.url.split("/").at(-1))}</strong><small>{file.mimetype} · {Math.max(1, Math.round(file.size / 1024))} KB</small></span><Download size={16} /></a>)}</div> : <p className="muted small-copy">Files shared with this task will appear here.</p>}</section>
    </div><aside className="task-detail-aside"><section className="panel aside-card"><span className="aside-icon"><ListTodo size={18} /></span><p className="eyebrow">A GOOD NEXT STEP</p><h3>Keep it moving</h3><p className="muted">A short update helps everyone know where the work stands.</p><Link className="button button-secondary button-full" to={`/projects/${projectId}?tab=tasks`}>Back to project tasks</Link></section><section className="aside-mini"><span>Project</span><Link to={`/projects/${projectId}`}>{task.project?.name || "Open project"}</Link></section></aside></div>{editing && <Modal title="Edit task" onClose={() => setEditing(false)}><form className="form-stack" onSubmit={saveTask}><Field label="Task title" name="title" value={taskForm.title} onChange={(event) => setTaskForm({ ...taskForm, title: event.target.value })} required maxLength={200} autoFocus /><Field as="textarea" label="Description" name="description" value={taskForm.description} onChange={(event) => setTaskForm({ ...taskForm, description: event.target.value })} maxLength={5000} rows={3} /><Field as="select" label="Assign to" name="assignedTo" value={taskForm.assignedTo} onChange={(event) => setTaskForm({ ...taskForm, assignedTo: event.target.value })}><option value="">Unassigned</option>{task.members?.map((member) => <option key={member.user?._id} value={member.user?._id}>{member.user?.fullName || member.user?.username}</option>)}</Field><Field type="date" label="Due date" name="dueDate" value={taskForm.dueDate} onChange={(event) => setTaskForm({ ...taskForm, dueDate: event.target.value })} /><Field as="select" label="Status" name="status" value={taskForm.status} onChange={(event) => setTaskForm({ ...taskForm, status: event.target.value })}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></Field>{formError && <p className="form-error">{formError}</p>}<div className="modal-actions"><Button type="button" variant="quiet" onClick={() => setEditing(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save task"}</Button></div></form></Modal>}{toastElement}</div>;
}
