import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, ClipboardList, Search } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../lib/api.js";
import { Badge, EmptyState, ErrorNotice, Loading, PageTitle, formatDate, formatStatus } from "../components/common.jsx";

export default function TasksPage() {
  const [params] = useSearchParams(); const query = params.get("q") || ""; const [items, setItems] = useState([]); const [filter, setFilter] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const projects = await api("/project"); const groups = await Promise.all(projects.map(async ({ project, role }) => ({ project, role, tasks: await api(`/tasks/${project._id}`) }))); setItems(groups.flatMap((group) => group.tasks.map((task) => ({ ...task, project: group.project, projectRole: group.role })))); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => items.filter((task) => (filter === "all" || task.status === filter) && `${task.title} ${task.description || ""} ${task.project.name}`.toLowerCase().includes(query.toLowerCase())), [items, filter, query]);
  if (loading) return <Loading />;
  return <div className="page-stack"><PageTitle eyebrow="YOUR WORKSPACE" title="All tasks" description="Keep an eye on the next steps across your projects." /><div className="toolbar"><div className="filter-search"><Search size={17} /><input aria-label="Search tasks" value={query} readOnly placeholder="Search tasks and projects" /></div><div className="filter-tabs">{[["all", "All"], ["todo", "Not started"], ["in_progress", "In progress"], ["done", "Done"]].map(([value, label]) => <button key={value} className={filter === value ? "filter-active" : ""} onClick={() => setFilter(value)}>{label}</button>)}</div></div>{error && <ErrorNotice error={{ message: error }} onRetry={load} />}
    {visible.length ? <section className="panel table-wrap"><table className="data-table"><thead><tr><th>Task</th><th>Project</th><th>Assignee</th><th>Status</th><th>Due date</th><th>Updated</th><th /></tr></thead><tbody>{visible.map((task) => <tr key={task._id}><td><Link className="table-primary" to={`/tasks/${task.project._id}/${task._id}`}>{task.title}</Link><small>{task.description || "No description"}</small></td><td><Link className="table-secondary" to={`/projects/${task.project._id}`}>{task.project.name}</Link></td><td>{task.assignedTo?.fullName || (task.assignedTo ? `@${task.assignedTo.username}` : "Unassigned")}</td><td><Badge tone={task.status === "in_progress" ? "dark" : "neutral"}>{formatStatus(task.status)}</Badge></td><td>{task.dueDate ? formatDate(task.dueDate) : "Not scheduled"}</td><td>{formatDate(task.updatedAt)}</td><td><Link className="icon-link" to={`/tasks/${task.project._id}/${task._id}`} aria-label={`Open ${task.title}`}><ArrowUpRight size={16} /></Link></td></tr>)}</tbody></table></section> : <EmptyState icon={ClipboardList} title={query ? "No tasks match that search" : "No tasks to show"} description={query ? "Try a different search or filter." : "When a task is added to one of your projects, it will show up here."} />}</div>;
}
