import { useEffect, useState } from "react";
import { Users } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../lib/api.js";
import { Avatar, Badge, Button, EmptyState, ErrorNotice, Loading, PageTitle, useToast } from "../components/common.jsx";

export default function TeamPage() {
  const [projects, setProjects] = useState([]); const [projectId, setProjectId] = useState(""); const [members, setMembers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const { showToast, toastElement } = useToast();
  async function loadProjects() { setLoading(true); try { const data = await api("/project"); setProjects(data); if (!projectId && data.length) setProjectId(data[0].project._id); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { loadProjects(); }, []);
  useEffect(() => { if (!projectId) return; api(`/project/${projectId}/members`).then(setMembers).catch((err) => setError(err.message)); }, [projectId]);
  const active = projects.find((item) => String(item.project._id) === String(projectId));
  const canManage = active?.role === "admin";
  async function changeRole(member, newRole) { try { await api(`/project/${projectId}/members/${member.user._id}`, { method: "PUT", body: JSON.stringify({ newRole }) }); setMembers(await api(`/project/${projectId}/members`)); showToast("Role updated."); } catch (err) { showToast(err.message); } }
  async function remove(member) { if (!window.confirm(`Remove ${member.user?.fullName || member.user?.username} from this project?`)) return; try { await api(`/project/${projectId}/members/${member.user._id}`, { method: "DELETE" }); setMembers(await api(`/project/${projectId}/members`)); showToast("Member removed."); } catch (err) { showToast(err.message); } }
  if (loading) return <Loading />;
  return <div className="page-stack"><PageTitle eyebrow="YOUR WORKSPACE" title="Team members" description="See who’s working together across your projects." action={canManage && <Link className="button button-primary" to={`/projects/${projectId}?tab=members`}>Add or manage members</Link>} />{error && <ErrorNotice error={{ message: error }} onRetry={loadProjects} />}{projects.length ? <><div className="toolbar"><label className="project-picker"><span>Project</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map(({ project }) => <option key={project._id} value={project._id}>{project.name}</option>)}</select></label><span className="toolbar-count">{members.length} people</span></div><section className="panel section-panel"><div className="section-heading"><div><p className="eyebrow">{active?.project.name}</p><h2>People on this project</h2>{!canManage && <p className="team-help">Ask a project admin to add people or change roles.</p>}</div><Link className="button button-secondary" to={`/projects/${projectId}?tab=members`}>Open project</Link></div>{members.map((member) => <div className="member-row member-row-expanded" key={member._id}><Avatar user={member.user} /><span className="member-row-name"><strong>{member.user?.fullName || member.user?.username}</strong><small>{member.user?.email}</small></span>{canManage && member.role !== "admin" ? <><select className="role-select" value={member.role} aria-label={`Role for ${member.user?.username}`} onChange={(event) => changeRole(member, event.target.value)}><option value="project_admin">Project Admin</option><option value="member">Member</option></select><Button variant="quiet" onClick={() => remove(member)}>Remove</Button></> : <Badge tone={member.role === "admin" ? "dark" : "neutral"}>{member.role.replace("_", " ")}</Badge>}</div>)}</section></> : <EmptyState icon={Users} title="No projects to show" description="Join a project to see the people you’ll be working with." action={<Link className="button button-primary" to="/projects">Explore projects</Link>} />}{toastElement}</div>;
}
